name: Labeling
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  
     runs-on: ubuntu-latest
     permissions:
       issues:
     steps:
       - name:
         uses:
 
  # uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
  uses: andymckay/labeler@1.0.4
 
 
           add-labels: triage
           repo-token: ${{ secrets.GITHUB_TOKEN }}
